project_name: aliyun-fc-releaser
release:
  github:
    owner: wsw0108
    name: aliyun-fc-releaser
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
       - README.md
       - LICENSE
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-{{ .ShortCommit }}"
